In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv("titanic.csv")
# print(df['Marital Status'].unique()) #list of unique values in column

# OneHotEncoding using sklearn

In [16]:
ohe = OneHotEncoder(drop='first') #drop first to avoid perfect multicollinearity
odf = pd.DataFrame(
    ohe.fit_transform(df[["Marital Status"]]).toarray()
)  # perform OHE by calling fit_transform() and storing the result as a
dfm = pd.concat([df, odf], axis=1)  # vertically/columnar combine of 2 dataframes
dfm = dfm.drop(
    ["Marital Status"], axis=1
)  # dropping the source column of OHE dataframe
dfm.columns = [
    [
        "PassengerId",
        "Survived",
        "Pclass",
        "Name",
        "Sex",
        "Age",
        "SibSp",
        "Parch",
        "Ticket",
        "Fare",
        "Cabin",
        "Embarked",
        #"Divorced",
        "Married-civ-spouse",
        "Married-spouse-absent",
        "Never-Married",
        "Separated",
        "Widowed",
    ]
]  # check if this manual mapping can be automated
dfm

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Married-civ-spouse,Married-spouse-absent,Never-Married,Separated,Widowed
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,0.0,0.0,0.0,0.0,1.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,0.0,0.0,0.0,0.0,1.0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.0,0.0,0.0,0.0,1.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,0.0,0.0,0.0,0.0,0.0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,NaN,S,1.0,0.0,0.0,0.0,0.0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,1.0,0.0,0.0,0.0,0.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.0,0.0,0.0,0.0,0.0
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C148,C,1.0,0.0,0.0,0.0,0.0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,NaN,Q,1.0,0.0,0.0,0.0,0.0

# OneHotEncoding using pandas.get_dummies() method.

In [17]:
df_pgd = pd.concat([df, pd.get_dummies(df["Marital Status"], drop_first=True, dtype=int)], axis=1).drop(["Marital Status"], axis=1) #includes redundancy elimination fixing perfect multicollinearity
df_pgd

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Married-civ-spouse,Married-spouse-absent,Never-married,Separated,Widowed
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,0,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,0,1
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,0,0,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,0,0,0,0,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",0,27.0,0,0,211536,13.0000,NaN,S,1,0,0,0,0
887,888,1,1,"Graham, Miss. Margaret Edith",1,19.0,0,0,112053,30.0000,B42,S,1,0,0,0,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,NaN,1,2,W./C. 6607,23.4500,NaN,S,1,0,0,0,0
889,890,1,1,"Behr, Mr. Karl Howell",0,26.0,0,0,111369,30.0000,C148,C,1,0,0,0,0
890,891,0,3,"Dooley, Mr. Patrick",0,32.0,0,0,370376,7.7500,NaN,Q,1,0,0,0,0

# Label Encoding using sklearn

In [73]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Sex']=le.fit_transform(df['Sex'])
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 13 columns]

# Label Encoding without using sklearn

In [13]:
df=pd.read_csv('titanic.csv')
#map() → works only on a Series(one field/column/domain), not on a DataFrame(tabular structure)
df['Survived']=df['Survived'].map({1:'yes',0:'no'}) #map to LabelEncode one column at a time
df[['Sex','Survived']]=df[['Sex','Survived']].replace({'male':0,'female':1,'yes':1,'no':0}) #replace to LabelEncode multiple columns in one shot
df

,PassengerId,Survived,Pclass,Name,Marital Status,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",Widowed,0,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Widowed,1,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",Widowed,1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",Divorced,1,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",Separated,0,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",Married-civ-spouse,0,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",Married-civ-spouse,1,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",Married-civ-spouse,1,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",Married-civ-spouse,0,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",Married-civ-spouse,0,32.0,0,0,370376,7.7500,NaN,Q

# A categorical column is said to have Nominal relationship when it has values logically unrelated.Ex: values present in Marital Status column.
# Ordinal relationship when it has values that are logically related. Ex: months of year, days of week, cancer type: Stage1, Stage2, Stage3, Stage4. Blood Pressure: Low, Medium, High
# When there only 2 values in a categorical column we use Label Encoding.
# Label Encoding can be applied on categorical columns with ordinal relationship or a categorical column with only 2 values.
# We apply OneHotEncoding when a categorical column had values with nominal relationships.
Practical rule of thumb
# If categories have order → use OrdinalEncoder
# If categories are just labels → use OneHotEncoder
# If encoding target variable → use LabelEncoder

In [4]:
#perform OHE for multiple columns in one shot
df_pgd = pd.concat([df, pd.get_dummies(df[["Marital Status", "Embarked"]], drop_first=True, dtype=int)], axis=1).drop(["Marital Status", "Embarked"], axis=1) #includes redundancy elimination fixing perfect multicollinearity
df_pgd

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Marital Status_Married-civ-spouse,Marital Status_Married-spouse-absent,Marital Status_Never-married,Marital Status_Separated,Marital Status_Widowed,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,0,0,0,0,1,0,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,0,0,0,0,1,0,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0,0,0,0,1,0,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,0,0,0,0,0,0,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,1,0,0,0,0,0,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,1,0,0,0,0,0,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,1,0,0,0,0,0,1
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,1,0,0,0,0,0,0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,1,0,0,0,0,1,0

In [18]:
# Ordinal Encoder
# 1. Enforce/control ordering using categories
# 2. 
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[['low', 'medium', 'high']])

data = [['low'], ['high'], ['medium']]
encoded = oe.fit_transform(data)

print(encoded)

[[0.]
 [2.]
 [1.]]

In [ ]:
oe = OrdinalEncoder(categories=[
    ['low', 'medium', 'high'],        # for col 1
    ['school', 'college', 'masters']  # for col 2
])
df[['col1', 'col2']] = oe.fit_transform(df[['col1', 'col2']]) #cols in same order as mentioned in categories

In [ ]:
# ColumnTransformer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
#quality is the name of the column where ordinal encoding is applied
#Sex, Embarked are the columns on which OHE is applied
preprocessor = ColumnTransformer([
    ('ord', OrdinalEncoder(categories=[['low','medium','high']]), ['quality']),
    ('nom', OneHotEncoder(), ['Sex', 'Embarked'])
])

In [ ]:
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

# Load data
df = pd.read_csv('titanic.csv')

# Target (keep it numeric — no need to convert to yes/no)
y = df['Survived']

# Features
X = df.drop(columns=['Survived'])

# Column groups
categorical_cols = ['Sex', 'Embarked']
numeric_cols = ['Age', 'Fare', 'SibSp', 'Parch', 'Pclass']

# --- Pipelines for each type ---

# Categorical pipeline
cat_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(drop='first', handle_unknown='ignore'))
])

# Numeric pipeline
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# --- ColumnTransformer ---
preprocessor = ColumnTransformer([
    ('cat', cat_pipeline, categorical_cols),
    ('num', num_pipeline, numeric_cols)
])

# --- Full pipeline ---
model = Pipeline([
    ('preprocessing', preprocessor),
    ('classifier', LogisticRegression())
])

# Fit model
model.fit(X, y)