In [50]:
import numpy as np
import pandas as pd
df=pd.read_csv('Titanic-Dataset.csv')
#c=["Marital_Status", "Sex", "Embarked"]
df_encoded = pd.get_dummies(df, columns=["Marital_Status", "Sex", "Embarked"])
df_encoded

     PassengerId  Survived  Pclass  ... Embarked_C  Embarked_Q  Embarked_S
0              1         0       3  ...      False       False        True
1              2         1       1  ...       True       False       False
2              3         1       3  ...      False       False        True
3              4         1       1  ...      False       False        True
4              5         0       3  ...      False       False        True
..           ...       ...     ...  ...        ...         ...         ...
886          887         0       2  ...      False       False        True
887          888         1       1  ...      False       False        True
888          889         0       3  ...      False       False        True
889          890         1       1  ...       True       False       False
890          891         0       3  ...      False        True       False

[891 rows x 21 columns]

In [1]:
a = 10
b = 20
print(b**a);

10240000000000

In [43]:
df['Marital Status']=dfa['marital.status'].iloc[:len(df)]

In [47]:
df

     PassengerId  Survived  Pclass  ... Cabin Embarked      Marital Status
0              1         0       3  ...   NaN        S             Widowed
1              2         1       1  ...   C85        C             Widowed
2              3         1       3  ...   NaN        S             Widowed
3              4         1       1  ...  C123        S            Divorced
4              5         0       3  ...   NaN        S           Separated
..           ...       ...     ...  ...   ...      ...                 ...
886          887         0       2  ...   NaN        S  Married-civ-spouse
887          888         1       1  ...   B42        S  Married-civ-spouse
888          889         0       3  ...   NaN        S  Married-civ-spouse
889          890         1       1  ...  C148        C  Married-civ-spouse
890          891         0       3  ...   NaN        Q  Married-civ-spouse

[891 rows x 13 columns]

In [24]:
df_adult.shape

(32561, 15)

In [30]:
marital_col = df_adult['marital.status'].iloc[:len(df)]
df['Marital Status'] = marital_col.values

In [29]:
marital_col

0                 Widowed
1                 Widowed
2                 Widowed
3                Divorced
4               Separated
              ...
886    Married-civ-spouse
887    Married-civ-spouse
888    Married-civ-spouse
889    Married-civ-spouse
890    Married-civ-spouse
Name: marital.status, Length: 891, dtype: str

In [32]:
df.to_csv("titanic_pot.csv", index=False)